/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Your API
 * API description
 * OpenAPI spec version: 1.0
 */
export interface CurrentUserResponse {
  id: string;
  firstName: string;
  lastName: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @nullable */
  avatar?: string | null;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  createdAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  updatedAt: string;
}

export interface LoginRequest {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @minLength 6 */
  password: string;
}

export interface LoginResponse {
  jwt: string;
}

export interface RegisterRequest {
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @minLength 6 */
  password: string;
  /** @minLength 1 */
  firstName: string;
  /** @minLength 1 */
  lastName: string;
  /** @minLength 1 */
  workspaceId?: string;
  /** @minLength 1 */
  workspaceName?: string;
}

export type HealthCheckControllerGetHealth200Status =
  (typeof HealthCheckControllerGetHealth200Status)[keyof typeof HealthCheckControllerGetHealth200Status];

export const HealthCheckControllerGetHealth200Status = {
  healthy: "healthy",
  unhealthy: "unhealthy",
} as const;

export type HealthCheckControllerGetHealth200ServicesDatabaseStatus =
  (typeof HealthCheckControllerGetHealth200ServicesDatabaseStatus)[keyof typeof HealthCheckControllerGetHealth200ServicesDatabaseStatus];

export const HealthCheckControllerGetHealth200ServicesDatabaseStatus = {
  healthy: "healthy",
  unhealthy: "unhealthy",
} as const;

export type HealthCheckControllerGetHealth200ServicesDatabase = {
  status?: HealthCheckControllerGetHealth200ServicesDatabaseStatus;
  /** Response time in milliseconds */
  responseTime?: number;
  /** Error message if unhealthy */
  error?: string;
};

export type HealthCheckControllerGetHealth200ServicesRedisStatus =
  (typeof HealthCheckControllerGetHealth200ServicesRedisStatus)[keyof typeof HealthCheckControllerGetHealth200ServicesRedisStatus];

export const HealthCheckControllerGetHealth200ServicesRedisStatus = {
  healthy: "healthy",
  unhealthy: "unhealthy",
} as const;

export type HealthCheckControllerGetHealth200ServicesRedis = {
  status?: HealthCheckControllerGetHealth200ServicesRedisStatus;
  /** Response time in milliseconds */
  responseTime?: number;
  /** Error message if unhealthy */
  error?: string;
};

export type HealthCheckControllerGetHealth200Services = {
  database?: HealthCheckControllerGetHealth200ServicesDatabase;
  redis?: HealthCheckControllerGetHealth200ServicesRedis;
};

export type HealthCheckControllerGetHealth200 = {
  status?: HealthCheckControllerGetHealth200Status;
  timestamp?: string;
  /** Uptime in seconds */
  uptime?: number;
  services?: HealthCheckControllerGetHealth200Services;
};
