/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Your API
 * API description
 * OpenAPI spec version: 1.0
 */
import type {
  CurrentUserResponse,
  LoginRequest,
  LoginResponse,
  RegisterRequest,
} from "./api-types.schemas";

import { customInstance } from "../../../lib/axios";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieve detailed profile information for the currently authenticated user including personal details, profile type, and associated salon information.
 * @summary Get current authenticated user
 */
export const authControllerGetCurrentUser = (
  options?: SecondParameter<typeof customInstance<CurrentUserResponse>>,
) => {
  return customInstance<CurrentUserResponse>(
    { url: `/auth/current`, method: "GET" },
    options,
  );
};
/**
 * Authenticate user with email and password
 * @summary User Login
 */
export const authControllerLogin = (
  loginRequest: LoginRequest,
  options?: SecondParameter<typeof customInstance<LoginResponse>>,
) => {
  return customInstance<LoginResponse>(
    {
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginRequest,
    },
    options,
  );
};
/**
 * Register a new user or update password for existing user
 * @summary User Registration
 */
export const authControllerRegister = (
  registerRequest: RegisterRequest,
  options?: SecondParameter<typeof customInstance<LoginResponse>>,
) => {
  return customInstance<LoginResponse>(
    {
      url: `/auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: registerRequest,
    },
    options,
  );
};
export type AuthControllerGetCurrentUserResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetCurrentUser>>
>;
export type AuthControllerLoginResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogin>>
>;
export type AuthControllerRegisterResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegister>>
>;
