/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Your API
 * API description
 * OpenAPI spec version: 1.0
 */
import type {
  CarControllerCreateCarHeaders,
  CarControllerGetWorkspaceCarsHeaders,
  CarControllerGetWorkspaceCarsTotalKmHeaders,
  CarWorkspaceResponse,
  CreateCarRequest,
  GetCarsByWorkspaceRequest,
  GetWorkspaceCarsTotalKmRequest,
  MutationResponse,
  WorkspaceCarTotalKmResponse,
} from './api-types.schemas'

import { customInstance } from '../../../lib/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Create a new car in the authenticated workspace. Accessible only by admin users.
 * @summary Create car
 */
export const carControllerCreateCar = (
  createCarRequest: CreateCarRequest,
  headers: CarControllerCreateCarHeaders,
  options?: SecondParameter<typeof customInstance<MutationResponse>>
) => {
  return customInstance<MutationResponse>(
    {
      url: `/workspace/car/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: createCarRequest,
    },
    options
  )
}
/**
 * Retrieve active cars from the authenticated workspace using filters, sorting, and pagination from request body.
 * @summary Get workspace cars
 */
export const carControllerGetWorkspaceCars = (
  headers: CarControllerGetWorkspaceCarsHeaders,
  _getCarsByWorkspaceRequest?: GetCarsByWorkspaceRequest,
  options?: SecondParameter<typeof customInstance<CarWorkspaceResponse[]>>
) => {
  return customInstance<CarWorkspaceResponse[]>(
    {
      url: `/workspace/car/workspace`,
      method: 'GET',
      headers: { 'Content-Type': 'application/json', ...headers },
    },
    options
  )
}
/**
 * Retrieve all active cars from the authenticated workspace with total kilometers in a date range for users assigned to a category.
 * @summary Get workspace cars total km
 */
export const carControllerGetWorkspaceCarsTotalKm = (
  getWorkspaceCarsTotalKmRequest: GetWorkspaceCarsTotalKmRequest,
  headers: CarControllerGetWorkspaceCarsTotalKmHeaders,
  options?: SecondParameter<typeof customInstance<WorkspaceCarTotalKmResponse[]>>
) => {
  return customInstance<WorkspaceCarTotalKmResponse[]>(
    {
      url: `/workspace/car/workspace/total-km`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: getWorkspaceCarsTotalKmRequest,
    },
    options
  )
}
export type CarControllerCreateCarResult = NonNullable<
  Awaited<ReturnType<typeof carControllerCreateCar>>
>
export type CarControllerGetWorkspaceCarsResult = NonNullable<
  Awaited<ReturnType<typeof carControllerGetWorkspaceCars>>
>
export type CarControllerGetWorkspaceCarsTotalKmResult = NonNullable<
  Awaited<ReturnType<typeof carControllerGetWorkspaceCarsTotalKm>>
>
