/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Your API
 * API description
 * OpenAPI spec version: 1.0
 */
import type {
  AssignUsersToCategoryRequest,
  CategoryControllerAssignUsersToCategoryHeaders,
  CategoryControllerCreateCategoryHeaders,
  CategoryControllerGetMyCategoriesHeaders,
  CategoryControllerGetWorkspaceCategoriesHeaders,
  CreateCategoryRequest,
  GetCategoriesResponse,
  GetMyCategoriesRequest,
  GetWorkspaceCategoriesRequest,
  MutationResponse,
} from './api-types.schemas'

import { customInstance } from '../../../lib/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Retrieve categories assigned to the authenticated user in the current workspace with optional filters, sorting, and pagination.
 * @summary Get my categories
 */
export const categoryControllerGetMyCategories = (
  headers: CategoryControllerGetMyCategoriesHeaders,
  getMyCategoriesRequest?: GetMyCategoriesRequest,
  options?: SecondParameter<typeof customInstance<GetCategoriesResponse[]>>
) => {
  return customInstance<GetCategoriesResponse[]>(
    {
      url: `/category/my-categories`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: getMyCategoriesRequest,
    },
    options
  )
}
/**
 * Retrieve categories from the authenticated workspace with optional filters, sorting, and pagination. Admin role required.
 * @summary Get workspace categories
 */
export const categoryControllerGetWorkspaceCategories = (
  headers: CategoryControllerGetWorkspaceCategoriesHeaders,
  getWorkspaceCategoriesRequest?: GetWorkspaceCategoriesRequest,
  options?: SecondParameter<typeof customInstance<GetCategoriesResponse[]>>
) => {
  return customInstance<GetCategoriesResponse[]>(
    {
      url: `/category/workspace`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: getWorkspaceCategoriesRequest,
    },
    options
  )
}
/**
 * Assign users from the authenticated workspace to a category. Accessible only by admin users.
 * @summary Assign users to category
 */
export const categoryControllerAssignUsersToCategory = (
  categoryId: string,
  assignUsersToCategoryRequest: AssignUsersToCategoryRequest,
  headers: CategoryControllerAssignUsersToCategoryHeaders,
  options?: SecondParameter<typeof customInstance<MutationResponse>>
) => {
  return customInstance<MutationResponse>(
    {
      url: `/category/${categoryId}/assign-users`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: assignUsersToCategoryRequest,
    },
    options
  )
}
/**
 * Create a new category in the authenticated workspace. Accessible only by manager users.
 * @summary Create category
 */
export const categoryControllerCreateCategory = (
  createCategoryRequest: CreateCategoryRequest,
  headers: CategoryControllerCreateCategoryHeaders,
  options?: SecondParameter<typeof customInstance<MutationResponse>>
) => {
  return customInstance<MutationResponse>(
    {
      url: `/category/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: createCategoryRequest,
    },
    options
  )
}
export type CategoryControllerGetMyCategoriesResult = NonNullable<
  Awaited<ReturnType<typeof categoryControllerGetMyCategories>>
>
export type CategoryControllerGetWorkspaceCategoriesResult = NonNullable<
  Awaited<ReturnType<typeof categoryControllerGetWorkspaceCategories>>
>
export type CategoryControllerAssignUsersToCategoryResult = NonNullable<
  Awaited<ReturnType<typeof categoryControllerAssignUsersToCategory>>
>
export type CategoryControllerCreateCategoryResult = NonNullable<
  Awaited<ReturnType<typeof categoryControllerCreateCategory>>
>
