/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Your API
 * API description
 * OpenAPI spec version: 1.0
 */
import type {
  CategoryControllerCreateCategoryHeaders,
  CategoryControllerGetMyCategoriesHeaders,
  CreateCategoryRequest,
  GetCategoriesResponse,
  GetMyCategoriesRequest,
  MutationResponse,
} from './api-types.schemas'

import { customInstance } from '../../../lib/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Retrieve categories assigned to the authenticated user in the current workspace with optional filters, sorting, and pagination.
 * @summary Get my categories
 */
export const categoryControllerGetMyCategories = (
  headers: CategoryControllerGetMyCategoriesHeaders,
  getMyCategoriesRequest?: GetMyCategoriesRequest,
  options?: SecondParameter<typeof customInstance<GetCategoriesResponse[]>>
) => {
  return customInstance<GetCategoriesResponse[]>(
    {
      url: `/workspace/category/my-categories`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: getMyCategoriesRequest,
    },
    options
  )
}
/**
 * Create a new category in the authenticated workspace. Accessible only by manager users.
 * @summary Create category
 */
export const categoryControllerCreateCategory = (
  createCategoryRequest: CreateCategoryRequest,
  headers: CategoryControllerCreateCategoryHeaders,
  options?: SecondParameter<typeof customInstance<MutationResponse>>
) => {
  return customInstance<MutationResponse>(
    {
      url: `/workspace/category/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: createCategoryRequest,
    },
    options
  )
}
export type CategoryControllerGetMyCategoriesResult = NonNullable<
  Awaited<ReturnType<typeof categoryControllerGetMyCategories>>
>
export type CategoryControllerCreateCategoryResult = NonNullable<
  Awaited<ReturnType<typeof categoryControllerCreateCategory>>
>
