/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Your API
 * API description
 * OpenAPI spec version: 1.0
 */
import type {
  GetReceiptsByWorkspaceRequest,
  MutationResponse,
  ReceiptControllerAddRecipeBody,
  ReceiptControllerAddRecipeHeaders,
  ReceiptControllerGetWorkspaceReceiptsHeaders,
  ReceiptWorkspaceResponse,
} from './api-types.schemas'

import { customInstance } from '../../../lib/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Create a new receipt in the authenticated workspace. Accessible by authenticated users.
 * @summary Create recipe
 */
export const receiptControllerAddRecipe = (
  receiptControllerAddRecipeBody: ReceiptControllerAddRecipeBody,
  headers: ReceiptControllerAddRecipeHeaders,
  options?: SecondParameter<typeof customInstance<MutationResponse>>
) => {
  const formData = new FormData()
  formData.append(`file`, receiptControllerAddRecipeBody.file)
  formData.append(`amount`, receiptControllerAddRecipeBody.amount.toString())
  formData.append(`place`, receiptControllerAddRecipeBody.place)
  formData.append(`date`, receiptControllerAddRecipeBody.date)
  formData.append(`categoryId`, receiptControllerAddRecipeBody.categoryId)

  return customInstance<MutationResponse>(
    { url: `/workspace/receipt`, method: 'POST', headers, data: formData },
    options
  )
}
/**
 * Retrieve receipts from the authenticated workspace using filters, sorting, and pagination from request body. Manager role required.
 * @summary Get workspace receipts
 */
export const receiptControllerGetWorkspaceReceipts = (
  headers: ReceiptControllerGetWorkspaceReceiptsHeaders,
  getReceiptsByWorkspaceRequest?: GetReceiptsByWorkspaceRequest,
  options?: SecondParameter<typeof customInstance<ReceiptWorkspaceResponse[]>>
) => {
  return customInstance<ReceiptWorkspaceResponse[]>(
    {
      url: `/workspace/receipt/workspace`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: getReceiptsByWorkspaceRequest,
    },
    options
  )
}
export type ReceiptControllerAddRecipeResult = NonNullable<
  Awaited<ReturnType<typeof receiptControllerAddRecipe>>
>
export type ReceiptControllerGetWorkspaceReceiptsResult = NonNullable<
  Awaited<ReturnType<typeof receiptControllerGetWorkspaceReceipts>>
>
