/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Your API
 * API description
 * OpenAPI spec version: 1.0
 */
import type {
  DeleteReceiptResponse,
  ExtractReceiptFromPdfItem,
  GetReceiptsByWorkspaceRequest,
  MutationResponse,
  ReceiptControllerAddManyRecipesBody,
  ReceiptControllerAddManyRecipesHeaders,
  ReceiptControllerAddRecipeBody,
  ReceiptControllerAddRecipeHeaders,
  ReceiptControllerDeleteReceiptHeaders,
  ReceiptControllerExtractReceiptFromPdfBody,
  ReceiptControllerExtractReceiptFromPdfHeaders,
  ReceiptControllerGetReceiptBlobHeaders,
  ReceiptControllerGetWorkspaceReceiptsHeaders,
  ReceiptWorkspaceResponse,
} from './api-types.schemas'

import { customInstance } from '../../../lib/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Create a new receipt in the authenticated workspace. Accessible by authenticated users.
 * @summary Create recipe
 */
export const receiptControllerAddRecipe = (
  receiptControllerAddRecipeBody: ReceiptControllerAddRecipeBody,
  headers: ReceiptControllerAddRecipeHeaders,
  options?: SecondParameter<typeof customInstance<MutationResponse>>
) => {
  const formData = new FormData()
  formData.append(`file`, receiptControllerAddRecipeBody.file)
  formData.append(`amount`, receiptControllerAddRecipeBody.amount.toString())
  formData.append(`place`, receiptControllerAddRecipeBody.place)
  formData.append(`date`, receiptControllerAddRecipeBody.date)
  formData.append(`categoryId`, receiptControllerAddRecipeBody.categoryId)

  return customInstance<MutationResponse>(
    { url: `/workspace/receipt`, method: 'POST', headers, data: formData },
    options
  )
}
/**
 * Create multiple receipts from a single uploaded file and multiple items { amount, categoryId, date }.
 * @summary Create many recipes
 */
export const receiptControllerAddManyRecipes = (
  receiptControllerAddManyRecipesBody: ReceiptControllerAddManyRecipesBody,
  headers: ReceiptControllerAddManyRecipesHeaders,
  options?: SecondParameter<typeof customInstance<MutationResponse>>
) => {
  const formData = new FormData()
  formData.append(`file`, receiptControllerAddManyRecipesBody.file)
  formData.append(`place`, receiptControllerAddManyRecipesBody.place)
  formData.append(`items`, receiptControllerAddManyRecipesBody.items)

  return customInstance<MutationResponse>(
    { url: `/workspace/receipt/create-many`, method: 'POST', headers, data: formData },
    options
  )
}
/**
 * Retrieve receipts from the authenticated workspace using filters, sorting, and pagination from request body. Manager role required.
 * @summary Get workspace receipts
 */
export const receiptControllerGetWorkspaceReceipts = (
  headers: ReceiptControllerGetWorkspaceReceiptsHeaders,
  getReceiptsByWorkspaceRequest?: GetReceiptsByWorkspaceRequest,
  options?: SecondParameter<typeof customInstance<ReceiptWorkspaceResponse[]>>
) => {
  return customInstance<ReceiptWorkspaceResponse[]>(
    {
      url: `/workspace/receipt/workspace`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: getReceiptsByWorkspaceRequest,
    },
    options
  )
}
/**
 * Upload a bank-statement PDF and extract debit transactions as amount, shopper, and date.
 * @summary Extract receipt transactions from PDF
 */
export const receiptControllerExtractReceiptFromPdf = (
  receiptControllerExtractReceiptFromPdfBody: ReceiptControllerExtractReceiptFromPdfBody,
  headers: ReceiptControllerExtractReceiptFromPdfHeaders,
  options?: SecondParameter<typeof customInstance<ExtractReceiptFromPdfItem[]>>
) => {
  const formData = new FormData()
  formData.append(`file`, receiptControllerExtractReceiptFromPdfBody.file)

  return customInstance<ExtractReceiptFromPdfItem[]>(
    { url: `/workspace/receipt/extract-from-pdf`, method: 'POST', headers, data: formData },
    options
  )
}
/**
 * Permanently delete a receipt in the authenticated workspace. Only workspace admins may call this endpoint.
 * @summary Delete receipt
 */
export const receiptControllerDeleteReceipt = (
  receiptId: string,
  headers: ReceiptControllerDeleteReceiptHeaders,
  options?: SecondParameter<typeof customInstance<DeleteReceiptResponse>>
) => {
  return customInstance<DeleteReceiptResponse>(
    { url: `/workspace/receipt/${receiptId}`, method: 'DELETE', headers },
    options
  )
}
/**
 * Retrieve the receipt file binary for a specific receipt in the authenticated workspace.
 * @summary Get receipt blob
 */
export const receiptControllerGetReceiptBlob = (
  receiptId: string,
  headers: ReceiptControllerGetReceiptBlobHeaders,
  options?: SecondParameter<typeof customInstance<Blob>>
) => {
  return customInstance<Blob>(
    { url: `/workspace/receipt/${receiptId}/blob`, method: 'GET', headers, responseType: 'blob' },
    options
  )
}
export type ReceiptControllerAddRecipeResult = NonNullable<
  Awaited<ReturnType<typeof receiptControllerAddRecipe>>
>
export type ReceiptControllerAddManyRecipesResult = NonNullable<
  Awaited<ReturnType<typeof receiptControllerAddManyRecipes>>
>
export type ReceiptControllerGetWorkspaceReceiptsResult = NonNullable<
  Awaited<ReturnType<typeof receiptControllerGetWorkspaceReceipts>>
>
export type ReceiptControllerExtractReceiptFromPdfResult = NonNullable<
  Awaited<ReturnType<typeof receiptControllerExtractReceiptFromPdf>>
>
export type ReceiptControllerDeleteReceiptResult = NonNullable<
  Awaited<ReturnType<typeof receiptControllerDeleteReceipt>>
>
export type ReceiptControllerGetReceiptBlobResult = NonNullable<
  Awaited<ReturnType<typeof receiptControllerGetReceiptBlob>>
>
