/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Your API
 * API description
 * OpenAPI spec version: 1.0
 */
import type {
  CreateRouteRequest,
  GetMyRoutesRequest,
  GetMyRoutesResponse,
  GetRoutesByWorkspaceRequest,
  MutationResponse,
  RouteControllerCreateRouteHeaders,
  RouteControllerGetMyRoutesHeaders,
  RouteControllerGetWorkspaceRoutesHeaders,
  RouteControllerUpdateRouteEndKmHeaders,
  RouteWorkspaceResponse,
  UpdateRouteEndKmRequest,
} from './api-types.schemas'

import { customInstance } from '../../../lib/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Create a new route in the authenticated workspace. The user is inferred from the JWT token.
 * @summary Create route
 */
export const routeControllerCreateRoute = (
  createRouteRequest: CreateRouteRequest,
  headers: RouteControllerCreateRouteHeaders,
  options?: SecondParameter<typeof customInstance<MutationResponse>>
) => {
  return customInstance<MutationResponse>(
    {
      url: `/workspace/route/create`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: createRouteRequest,
    },
    options
  )
}
/**
 * Retrieve routes created by the authenticated user in the current workspace with optional filters, sorting, and pagination.
 * @summary Get my routes
 */
export const routeControllerGetMyRoutes = (
  headers: RouteControllerGetMyRoutesHeaders,
  getMyRoutesRequest?: GetMyRoutesRequest,
  options?: SecondParameter<typeof customInstance<GetMyRoutesResponse[]>>
) => {
  return customInstance<GetMyRoutesResponse[]>(
    {
      url: `/workspace/route/my-routes`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: getMyRoutesRequest,
    },
    options
  )
}
/**
 * Retrieve routes from the authenticated workspace using filters, sorting, and pagination from request body. Manager role required.
 * @summary Get workspace routes
 */
export const routeControllerGetWorkspaceRoutes = (
  headers: RouteControllerGetWorkspaceRoutesHeaders,
  getRoutesByWorkspaceRequest?: GetRoutesByWorkspaceRequest,
  options?: SecondParameter<typeof customInstance<RouteWorkspaceResponse[]>>
) => {
  return customInstance<RouteWorkspaceResponse[]>(
    {
      url: `/workspace/route/workspace`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: getRoutesByWorkspaceRequest,
    },
    options
  )
}
/**
 * Update only the end km of a route in the authenticated workspace. The authenticated user must own the route.
 * @summary Update route end km
 */
export const routeControllerUpdateRouteEndKm = (
  routeId: string,
  updateRouteEndKmRequest: UpdateRouteEndKmRequest,
  headers: RouteControllerUpdateRouteEndKmHeaders,
  options?: SecondParameter<typeof customInstance<MutationResponse>>
) => {
  return customInstance<MutationResponse>(
    {
      url: `/workspace/route/update/${routeId}/end-km`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: updateRouteEndKmRequest,
    },
    options
  )
}
export type RouteControllerCreateRouteResult = NonNullable<
  Awaited<ReturnType<typeof routeControllerCreateRoute>>
>
export type RouteControllerGetMyRoutesResult = NonNullable<
  Awaited<ReturnType<typeof routeControllerGetMyRoutes>>
>
export type RouteControllerGetWorkspaceRoutesResult = NonNullable<
  Awaited<ReturnType<typeof routeControllerGetWorkspaceRoutes>>
>
export type RouteControllerUpdateRouteEndKmResult = NonNullable<
  Awaited<ReturnType<typeof routeControllerUpdateRouteEndKm>>
>
