/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Your API
 * API description
 * OpenAPI spec version: 1.0
 */
import type {
  GetUsersByWorkspaceRequest,
  MutationResponse,
  UserControllerDeleteUserHeaders,
  UserControllerGetWorkspaceUsersHeaders,
  UserWorkspaceResponse,
} from './api-types.schemas'

import { customInstance } from '../../../lib/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Retrieve active users from the authenticated workspace using filters, sorting, and pagination from request body.
 * @summary Get workspace users
 */
export const userControllerGetWorkspaceUsers = (
  headers: UserControllerGetWorkspaceUsersHeaders,
  getUsersByWorkspaceRequest?: GetUsersByWorkspaceRequest,
  options?: SecondParameter<typeof customInstance<UserWorkspaceResponse[]>>
) => {
  return customInstance<UserWorkspaceResponse[]>(
    {
      url: `/user/workspace`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...headers },
      data: getUsersByWorkspaceRequest,
    },
    options
  )
}
/**
 * Soft delete a user from the authenticated workspace. Accessible only by admin users.
 * @summary Delete user
 */
export const userControllerDeleteUser = (
  userId: string,
  headers: UserControllerDeleteUserHeaders,
  options?: SecondParameter<typeof customInstance<MutationResponse>>
) => {
  return customInstance<MutationResponse>(
    { url: `/user/${userId}`, method: 'DELETE', headers },
    options
  )
}
export type UserControllerGetWorkspaceUsersResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetWorkspaceUsers>>
>
export type UserControllerDeleteUserResult = NonNullable<
  Awaited<ReturnType<typeof userControllerDeleteUser>>
>
