/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Your API
 * API description
 * OpenAPI spec version: 1.0
 */
import type { WorkspacePublicResponse } from './api-types.schemas'

import { customInstance } from '../../../lib/axios'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Public endpoint that returns a single workspace by id.
 * @summary Get workspace by id
 */
export const workspaceControllerGetWorkspaceById = (
  workspaceId: string,
  options?: SecondParameter<typeof customInstance<WorkspacePublicResponse>>
) => {
  return customInstance<WorkspacePublicResponse>(
    { url: `/workspace/${workspaceId}`, method: 'GET' },
    options
  )
}
export type WorkspaceControllerGetWorkspaceByIdResult = NonNullable<
  Awaited<ReturnType<typeof workspaceControllerGetWorkspaceById>>
>
