/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthGuardRouteImport } from './routes/_auth-guard'
import { Route as AuthGuardManagerGuardRouteImport } from './routes/_auth-guard/_manager-guard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGuardRoute = AuthGuardRouteImport.update({
  id: '/_auth-guard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGuardManagerGuardRoute = AuthGuardManagerGuardRouteImport.update({
  id: '/_manager-guard',
  getParentRoute: () => AuthGuardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthGuardManagerGuardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthGuardManagerGuardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth-guard': typeof AuthGuardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth-guard/_manager-guard': typeof AuthGuardManagerGuardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register'
  id:
    | '__root__'
    | '/_auth-guard'
    | '/login'
    | '/register'
    | '/_auth-guard/_manager-guard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthGuardRoute: typeof AuthGuardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-guard': {
      id: '/_auth-guard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-guard/_manager-guard': {
      id: '/_auth-guard/_manager-guard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthGuardManagerGuardRouteImport
      parentRoute: typeof AuthGuardRoute
    }
  }
}

interface AuthGuardRouteChildren {
  AuthGuardManagerGuardRoute: typeof AuthGuardManagerGuardRoute
}

const AuthGuardRouteChildren: AuthGuardRouteChildren = {
  AuthGuardManagerGuardRoute: AuthGuardManagerGuardRoute,
}

const AuthGuardRouteWithChildren = AuthGuardRoute._addFileChildren(
  AuthGuardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthGuardRoute: AuthGuardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
