/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthGuardRouteImport } from './routes/_auth-guard'
import { Route as AuthGuardIndexRouteImport } from './routes/_auth-guard/index'
import { Route as AuthGuardManagerGuardRouteImport } from './routes/_auth-guard/_manager-guard'
import { Route as AuthGuardManagerGuardUsersRouteImport } from './routes/_auth-guard/_manager-guard/users'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGuardRoute = AuthGuardRouteImport.update({
  id: '/_auth-guard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGuardIndexRoute = AuthGuardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthGuardRoute,
} as any)
const AuthGuardManagerGuardRoute = AuthGuardManagerGuardRouteImport.update({
  id: '/_manager-guard',
  getParentRoute: () => AuthGuardRoute,
} as any)
const AuthGuardManagerGuardUsersRoute =
  AuthGuardManagerGuardUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthGuardManagerGuardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthGuardIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/users': typeof AuthGuardManagerGuardUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthGuardIndexRoute
  '/users': typeof AuthGuardManagerGuardUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth-guard': typeof AuthGuardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth-guard/_manager-guard': typeof AuthGuardManagerGuardRouteWithChildren
  '/_auth-guard/': typeof AuthGuardIndexRoute
  '/_auth-guard/_manager-guard/users': typeof AuthGuardManagerGuardUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/' | '/users'
  id:
    | '__root__'
    | '/_auth-guard'
    | '/login'
    | '/register'
    | '/_auth-guard/_manager-guard'
    | '/_auth-guard/'
    | '/_auth-guard/_manager-guard/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthGuardRoute: typeof AuthGuardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-guard': {
      id: '/_auth-guard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-guard/': {
      id: '/_auth-guard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthGuardIndexRouteImport
      parentRoute: typeof AuthGuardRoute
    }
    '/_auth-guard/_manager-guard': {
      id: '/_auth-guard/_manager-guard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthGuardManagerGuardRouteImport
      parentRoute: typeof AuthGuardRoute
    }
    '/_auth-guard/_manager-guard/users': {
      id: '/_auth-guard/_manager-guard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthGuardManagerGuardUsersRouteImport
      parentRoute: typeof AuthGuardManagerGuardRoute
    }
  }
}

interface AuthGuardManagerGuardRouteChildren {
  AuthGuardManagerGuardUsersRoute: typeof AuthGuardManagerGuardUsersRoute
}

const AuthGuardManagerGuardRouteChildren: AuthGuardManagerGuardRouteChildren = {
  AuthGuardManagerGuardUsersRoute: AuthGuardManagerGuardUsersRoute,
}

const AuthGuardManagerGuardRouteWithChildren =
  AuthGuardManagerGuardRoute._addFileChildren(
    AuthGuardManagerGuardRouteChildren,
  )

interface AuthGuardRouteChildren {
  AuthGuardManagerGuardRoute: typeof AuthGuardManagerGuardRouteWithChildren
  AuthGuardIndexRoute: typeof AuthGuardIndexRoute
}

const AuthGuardRouteChildren: AuthGuardRouteChildren = {
  AuthGuardManagerGuardRoute: AuthGuardManagerGuardRouteWithChildren,
  AuthGuardIndexRoute: AuthGuardIndexRoute,
}

const AuthGuardRouteWithChildren = AuthGuardRoute._addFileChildren(
  AuthGuardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthGuardRoute: AuthGuardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
